name: Go Test
on: [push, pull_request]
jobs:
  tidy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19.1
      - name: Get Dependencies
        run: go get -v -t -d ./...
      - name: Run Tests
        run: go test -v ./...
