name: Go Test
on: [push, pull_request]
jobs:
  tidy:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19.1
      - name: Create .env file
        run: |
          echo "PORT=3000" >> .env
          echo "APP_ENV=test" >> .env
      - name: Get Dependencies
        run: go get -v -t -d ./...
      - name: Run Tests
        run: go test -v
